# Generated by Django 3.2 on 2021-12-07 19:01

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_auto_20211207_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18, samples=None, verbose_name='HEX-код'),
        ),
    ]
