# Generated by Django 3.2 on 2022-01-09 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_alter_recipe_shopping_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritehasrecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_favorite', to='recipe.recipe'),
        ),
    ]
