### Авторизация
POST http://127.0.0.1:8000/auth/token/login/
Content-Type: application/json

{
    "username": "rwerwrw",
    "password": "ddedewsd3ewsde"
}

###

@token = 7fbcc64418dd8103efbd83e4d5a25b9a9fc298a0

###

POST http://127.0.0.1:8000/auth/token/logout/
Authorization: Token {{token}}

###






### endpoint /auth/

GET http://127.0.0.1:8000/auth/users/me/
Authorization: Token {{token}}

###

GET http://127.0.0.1:8000/auth/users/1/
Authorization: Token {{token}}
###

POST http://127.0.0.1:8000/auth/users/
Content-Type: application/json

{
    "username": "rwerwrw",
    "password": "ddedewsd3ewsde"
}
###

GET http://127.0.0.1:8000/auth/users/2/
Authorization: Token {{token}}

###



### endpoint /users/
GET http://127.0.0.1:8000/api/users/
###
GET http://127.0.0.1:8000/api/users/2/
###
GET http://127.0.0.1:8000/api/users/me/
###
POST http://127.0.0.1:8000/api/users/
Content-Type: application/json

{

    "email": "vpupkin@yandex.ru",
    "username": "vasya.pupkin",
    "first_name": "Вася",
    "last_name": "Пупкин",
    "password": "Qwerty123"

}

### endpoint /tags/
GET http://127.0.0.1:8000/api/v1/tags/
###
GET http://127.0.0.1:8000/api/v1/tags/3/
###



### endpoint /ingredients/
GET http://127.0.0.1:8000/api/v1/ingredients/
###
GET http://127.0.0.1:8000/api/v1/ingredients/?search=кост
###
GET http://127.0.0.1:8000/api/v1/ingredients/5/
###